/* autogenerated by Processing revision 1286 on 2022-08-30 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class PolePainter extends PApplet {

 public void setup(){
}


 public void draw(){
  
}


  public void settings() { size(1400, 900); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "PolePainter" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
